dist: trusty
os: linux
language: cpp
sudo: required

script:
  - sudo wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - sudo tar xzf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - sudo ./bootstrap.sh --prefix=/usr/local
  - sudo ./bootstrap.sh --with-libraries=program_options,system --prefix=/usr/local
  - sudo ./b2 link=shared threading=multi variant=release
  - sudo ./b2 install
  - cd .. 
  - CC=gcc-7 CXX=g++-7 make

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
